apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: kind-worker
      containers:
      - name: backend
        image: backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: test
spec:
  selector:
    app: backend
  ports:
    - name: main-port
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: internal-port
      protocol: TCP
      port: 8080
      targetPort: 8080