apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: client-l3-policy
  namespace: test
spec:
  endpointSelector:
    matchLabels:
      app: client
  ingress:
    - {}
  egress:
    - toEndpoints:
        - matchLabels:
            app: backend
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP